export default {
  PRIMARY_COLOR1: '#93B1FE',
  PRIMARY_COLOR2: '#93B1FE',
  PRIMARY_COLOR3: '#CBD3F7',
  SECONDARY_COLOR1: '#F595B8',
  SECONDARY_COLOR2: '#f9bfd4',
  TEXT_COLOR1: 'white',
  ICON_COLOR1: 'white',
  WHITE_SHADE1: '#f5f5f5',
  BAR_FILL_COLOR1: 'white',
  TEXT_COLOR2: 'black',
  BACKGROUND_COLOR: '#F5F4FC',
  BACKGROUND_COLOR2: 'white',
};
// export default {
//   PRIMARY_COLOR1: '#93B1FE',
//   PRIMARY_COLOR2: '#93B1FE',
//   PRIMARY_COLOR3: '#CBD3F7',
//   SECONDARY_COLOR1: '#F595B8',
//   SECONDARY_COLOR2: '#f9bfd4',
//   TEXT_COLOR1: 'white',
//   ICON_COLOR1: 'white',
//   WHITE_SHADE1: '#f5f5f5',
//   BAR_FILL_COLOR1: 'white',
//   TEXT_COLOR2: 'black',
//   BACKGROUND_COLOR: '#F5F4FC',
//   BACKGROUND_COLOR2: 'white',
// };
// export default {
//   PRIMARY_COLOR1: '#E00072',
//   PRIMARY_COLOR2: '#E00072',
//   PRIMARY_COLOR3: '#E04299',
//   SECONDARY_COLOR1: '#6200ED',
//   SECONDARY_COLOR2: '#BB86FC',
//   TEXT_COLOR1: 'white',
//   ICON_COLOR1: 'white',
//   WHITE_SHADE1: '#f5f5f5',
//   BAR_FILL_COLOR1: 'white',
//   TEXT_COLOR2: 'black',
//   BACKGROUND_COLOR: '#F5F4FC',
//   BACKGROUND_COLOR2: 'white',
// };
